[server]
port = 3003

[logger]
#  TRACE: 'trace',
#  DEBUG: 'debug',
#  INFO: 'info',
#  WARN: 'warn',
#  ERROR: 'error',
#  FATAL: 'fatal'
level = "trace"
makePretty = true

[application]
environment = "development"
imgixBaseURL = ""

[dataStore]
region = ""
bucketName = ""
environment = "development"
accessKeyId = ""
secretAccessKey = ""

[objectStore]
region = ""
bucketName = ""
environment = "development"
accessKeyId = ""
secretAccessKey = ""

[mediaConvert]
role = ""
endpoint = ""
accessKeyId = ""
secretAccessKey = ""

[localObjectStore]
directory = ""
