[server]
port = 3003

[logger]
#  TRACE: 'trace',
#  DEBUG: 'debug',
#  INFO: 'info',
#  WARN: 'warn',
#  ERROR: 'error',
#  FATAL: 'fatal'
level = "trace"
makePretty = true

[dataStore]
region = ""
bucketName = ""
environment = "development"
accessKeyId = ""
secretAccessKey = ""
