[logger]
#  TRACE: 'trace',
#  DEBUG: 'debug',
#  INFO: 'info',
#  WARN: 'warn',
#  ERROR: 'error',
#  FATAL: 'fatal'
level = "trace"
makePretty = true

[server]
port = 3033

[dynamoDB]
region = ""
# Endpoints: https://docs.aws.amazon.com/general/latest/gr/ddb.html
endpoint = ""
accessKeyId = ""
secretAccessKey = ""
applicationName = ""
environment = "development"
