[logger]
#  TRACE: 'trace',
#  DEBUG: 'debug',
#  INFO: 'info',
#  WARN: 'warn',
#  ERROR: 'error',
#  FATAL: 'fatal'
level = "trace"
makePretty = true

[server]
port = 3033

[dataStore]
environment = ""

[dynamoDB]
region = ""
# Endpoints: https://docs.aws.amazon.com/general/latest/gr/ddb.html
endpoint = ""
accessKeyId = ""
secretAccessKey = ""

[objectService]
endpoint = ""
scope = "adkavy-development"
token = ""

[pages]
# Set to true to enable page caching.
cache = true
